### ISSUE TITLE
json: fails to parse \uNNNN

### ISSUE THREAD

**Issue by ppentchev** [facet-rs/facet#530]
Hi,

ICBW here, but I think `\uNNNN` is standard in JSON, at least according to the "escape" rule at https://json.org/

So should this indeed fail?

``` rust
#![deny(missing_docs)]
#![deny(clippy::missing_docs_in_private_items)]
// SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
// SPDX-License-Identifier: BSD-2-Clause
//! Demonstrate a facet-json failure to parse weird and not-so-weird characters.

#[cfg(test)]
#[expect(clippy::panic_in_result_fn, reason = "this is a test suite")]
#[expect(clippy::print_stdout, reason = "this is a test suite")]
mod tests {
    /// Something `facet-json` has no trouble parsing.
    const OK_JSON: &str = "\"This is fine.\"";

    /// The result of the successful parse.
    const OK_EXPECTED: &str = "This is fine.";

    /// Something `facet-json` does not parse correctly.
    const FAIL_JSON: &str = "\"This\\u0020is fine.\"";

    /// The expected result of the failed parse.
    const FAIL_EXPECTED: &str = "This is fine.";

    use anyhow::{Result, anyhow};

    #[test]
    fn parse_ok() -> Result<()> {
        println!("Attempting to parse {OK_JSON}");
        let parsed_ok = facet_json::from_str::<String>(OK_JSON)
            .map_err(|err| anyhow!("Could not parse {OK_JSON:?}: {err}"))?;
        assert_eq!(parsed_ok, OK_EXPECTED);
        Ok(())
    }

    #[test]
    fn parse_fail() -> Result<()> {
        println!("Attempting to parse {FAIL_JSON}");
        let parsed_fail = facet_json::from_str::<String>(FAIL_JSON)
            .map_err(|err| anyhow!("Could not parse {FAIL_JSON:?}: {err}"))?;
        assert_eq!(parsed_fail, FAIL_EXPECTED);
        Ok(())
    }
}
```

Thanks in advance for looking at this, and keep up the great work!

G'luck,
Peter

**Comment by ppentchev** [comment]
Ah, so at the last moment I decided not to put up a link to a repo containing the full source, but only the failing file. This was built using:

``` toml
# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

[package]
name = "facet-json-parse-unicode"
version = "0.1.0"
rust-version = "1.86"
edition = "2024"
authors = ["Peter Pentchev <roam@ringlet.net>"]
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0.46"
facet = "= 0.18.6"
facet-json = "= 0.23.0"
```
